version: "3.8"

services:
  prom-server:
    image: prom/prometheus
    container_name: prom-server
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    env_file:
      - .env
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    env_file:
      - .env